export const data = [
  {
    Matricula: "1001",
    Nome: "Giorno Giovana",
    Imagem: "https://i.pinimg.com/736x/d3/9c/6b/d39c6b72acf0c080eb734cda0a46e708.jpg",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },

  {
    Matricula: "1002",
    Nome: "Goku",
    Imagem: "https://ovicio.com.br/wp-content/uploads/2023/09/20231022-cropped-20230928-dragon-ball-goku.jpg",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
        Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 58,
        RE1: "-",
        ME1: 58,
        F1: 1,
        N2: 51,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 54,
        N3: 53,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 57,
        RE3: "-",
        ME3: 80,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: 43,
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 54,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 70,
        RE2: "-",
        ME2: 80,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 30,
        MD: 29,
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 10,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: 39,
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "11",
    Nome: "Naruto Uzumaki",
    Imagem: "https://th.bing.com/th/id/OIP.sXqt7QTSqjgZPV85BAzJZgHaEJ?w=315&h=180&c=7&r=0&o=7&cb=ucfimgc2&pid=1.7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "12",
    Nome: "Rafael",
    Imagem: "https://th.bing.com/th/id/OIP.Q72UTXBWIPz6UQIWuStPPwHaG8?w=172&h=180&c=7&r=0&o=7&cb=ucfimgc2&pid=1.7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "13",
    Nome: "Leonardo",
    Imagem: "https://tse3.mm.bing.net/th/id/OIP.nUvj4QCEFGzbwoHsJ4QXhAAAAA?cb=ucfimgc2&pid=ImgDet&w=185&h=230&c=7&o=7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "14",
    Nome: "Michelangelo",
    Imagem: "https://tse2.mm.bing.net/th/id/OIP.1PMR6uEKiCpxJNtkTif2SAHaHk?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "15",
    Nome: "Donatelo",
    Imagem: "https://tse4.mm.bing.net/th/id/OIP.7_4EDSAS2kDqRGVmiyLSUQHaHa?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "16",
    Nome: "Luffy",
    Imagem: "https://th.bing.com/th/id/OIP.ZOSJd3q4PX5WRPp6jXNo8QHaPg?w=115&h=180&c=7&r=0&o=7&cb=ucfimgc2&pid=1.7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "17",
    Nome: "Vegeta",
    Imagem: "https://th.bing.com/th/id/OIP.XaBsoeC5jxBanzipawnMRgHaQm?w=115&h=180&c=7&r=0&o=7&cb=ucfimgc2&pid=1.7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "18",
    Nome: "Gui",
    Imagem: "https://th.bing.com/th/id/OIP.CY-YH0XIlbb6WnrJB85gigHaEK?w=330&h=185&c=7&r=0&o=7&cb=ucfimgc2&pid=1.7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "19",
    Nome: "Estopa",
    Imagem: "https://th.bing.com/th/id/OIP.P-E5Yf4pj3XiD15_t_r1QwHaEI?w=281&h=180&c=7&r=0&o=7&cb=ucfimgc2&pid=1.7&rm=3",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
  {
    Matricula: "20",
    Nome: "Sasori",
    Imagem: "https://criticalhits.com.br/wp-content/uploads/2022/04/sasori.jpg",
    Sigla: "3A",
    Curso:
      "Técnico em Informática Integrado ao Ensino Médio, Técnico Integrado, 3º Período, Matriz 293, Turno Matutino (2025)",
    Curso_Novo: "Informática",
    Ensino: "Técnico Integrado",
    Ano: "3º Ano",
    Matriz: "293",
    Turno: "Matutino",
    Disciplinas: [
      {
        NomeDisciplina: "Biologia",
        Diario: 33001,
        Disciplina: "INT.0003  - Biologia",
        CH: "80 Aulas",
        Aulas: 56,
        Faltas: 3,
        Freq: "94,64%",
        Situacao: "Cursando",
        N1: 78,
        RE1: "-",
        ME1: 78,
        F1: 1,
        N2: 91,
        RE2: "-",
        ME2: 91,
        F2: 0,
        MD1: 84,
        N3: 63,
        RE3: "-",
        ME3: 63,
        F3: 2,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 31,
        MD: "58",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Desenvolvimento Mobile",
        Diario: 33002,
        Disciplina: "INT.0685  - Desenvolvimento Mobile",
        CH: "80 Aulas",
        Aulas: 48,
        Faltas: 5,
        Freq: "89,58%",
        Situacao: "Cursando",
        N1: "",
        RE1: "",
        ME1: "",
        F1: "",
        N2: "",
        RE2: "",
        ME2: "",
        F2: "",
        MD1: "",
        N3: 87,
        RE3: "-",
        ME3: 87,
        F3: 3,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 2,
        MD2: 43,
        MD: "43",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Educação Física",
        Diario: 33003,
        Disciplina: "INT.0148  - Educação Física",
        CH: "80 Aulas",
        Aulas: 58,
        Faltas: 0,
        Freq: "100%",
        Situacao: "Cursando",
        N1: 94,
        RE1: "-",
        ME1: 94,
        F1: 0,
        N2: 100,
        RE2: "-",
        ME2: 100,
        F2: 0,
        MD1: 97,
        N3: 81,
        RE3: "-",
        ME3: 81,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 40,
        MD: "69",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Empreendedorismo e Inovação",
        Diario: 33004,
        Disciplina: "INT.0684  - Empreendedorismo e Inovação",
        CH: "80 Aulas",
        Aulas: 68,
        Faltas: 2,
        Freq: "97,05%",
        Situacao: "Cursando",
        N1: 72,
        RE1: "-",
        ME1: 72,
        F1: 2,
        N2: 89,
        RE2: "-",
        ME2: 89,
        F2: 0,
        MD1: 80,
        N3: 77,
        RE3: "-",
        ME3: 77,
        F3: 0,
        N4: "-",
        RE4: "-",
        ME4: 0,
        F4: 0,
        MD2: 38,
        MD: "59",
        NAF: "-",
        MFD: "-",
      },
      {
        NomeDisciplina: "Fábrica de Software III",
        Diario: 33005,
        Disciplina: "INT.0683  - Fábrica de Software III",
        CH: "80 Aulas",
        Aulas: 80,
        Faltas: 6,
        Freq: "92,5%",
        Situacao: "Aprovado",
        N1: 91,
        RE1: "-",
        ME1: 91,
        F1: 3,
        N2: 64,
        RE2: "80",
        ME2: 80,
        F2: 3,
        MD1: 85,
        N3: "",
        RE3: "",
        ME3: "",
        F3: "",
        N4: "",
        RE4: "",
        ME4: "",
        F4: "",
        MD2: "",
        MD: "85",
        NAF: "-",
        MFD: "85",
      },
    ],
  },
];
